config/routes.rb
Rails.application.routes.draw do

  resources :movies do
    resources :reviews, except: [:show, :index]
  end
  devise_for :users
  resources :pins do
    member do
      put "like", to: "pins#upvote"
    end
  end
  root "movies#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :user
  has_many :reviews
  has_attached_file :image_movie, styles: { medium: "400x600＃" }
  validates_attachment_content_type :image_movie, content_type: /\Aimage\/.*\z/

end

app/models/pin.rb
class Pin < ApplicationRecord
  acts_as_votable
  belongs_to :user
  has_attached_file :image, styles: { medium: "300x300>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :movies
  has_many :pins
  has_many :reviews, dependent: :destroy
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    # @reviews = @movie.reviews
    @reviews = Review.where(movie_id: @movie.id).order("created_at DESC")
  end

  # GET /movies/new
  def new
    @movie = current_user.movies.new

  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = current_user.movies.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :description, :movie_length, :director, :rating, :image_movie)
    end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :find_pin, only: [:show, :edit, :update, :destroy, :upvote]
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @pins = Pin.all.order("created_at DESC")
  end

  def new
    @pin = current_user.pins.new
  end

  def create
    @pin = current_user.pins.new(pin_params)
    if @pin.save
      redirect_to @pin, notice: "Successfully created new Pin"
    else
      render :new
    end
  end

  def show
    
  end

  def edit
  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: "OK update"
    else
      render :edit
    end
  end

  def destroy
    @pin.destroy
    redirect_to root_path, notice: "Successfully delete one Pin"
  end

  def upvote
    @pin.upvote_by current_user
    redirect_to :back
  end

  private

  def find_pin
    @pin = Pin.find(params[:id])
  end

  def pin_params
    params.require(:pin).permit(:title, :description, :image)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :set_movie, only: [:new, :create]
  before_action :authenticate_user!


  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create

    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.movie_id = @movie.id

    respond_to do |format|
      if @review.save
        format.html { redirect_to @movie, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end
    def set_movie
      @movie = Movie.find(params[:movie_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:rating, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_header.html.haml
%nav.navbar.navbar-default
  .container
    .navbar-brand
      = link_to "Pin Board", root_path

    %ul.nav.navbar-nav
      %li= link_to "Pin Board", pins_path
      %li= link_to "Movies", movies_path
      %form.navbar-form.navbar-right{:role => "search"}
        .form-group
          %input.form-control{:type => "text", :placeholder => "Search"}
        %button.btn.btn-default{:type => "submit"} Submit
    - if user_signed_in?
      %ul.nav.navbar-nav.navbar-right
        %li= link_to "New Pin", new_pin_path
        %li= link_to "Account", edit_user_registration_path
        %li= link_to "Sign Out", destroy_user_session_path, method: :delete
    - else
      %ul.nav.navbar-nav.navbar-right
        %li= link_to "Sign Up", new_user_registration_path
        %li= link_to "Sign In", new_user_session_path

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title PinBoard
    = csrf_meta_tags

    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    = render 'layouts/header'

    .container
      - flash.each do |name, msg|
        = content_tag :div, msg, class: "alert alert-info"
      =yield

app/views/movies/_form.html.haml
= simple_form_for @movie, html:{multipart:true} do |f|
  = f.error_notification
  .form-inputs
    = f.input :title
    = f.input :description
    = f.input :movie_length
    = f.input :director
    = f.input :rating
    = f.input :image_movie
  .form-actions
    = f.button :submit

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.haml
#movies
  - if !user_signed_in?
    .jumbotron
      %h1 Your Favorite Movies Reviewed
      %p Hashtag hoodie mumblecore selfies. Authentic keffiyeh leggings Kickstarter, narwhal jean shorts XOXO Vice Austin cadigan. Organic drinking vinegar freegan pickled.
      %p= link_to "Sign Up To Write A Review", new_user_registration_path, class: "btn btn-primary btn-lg"

  %row
    - @movies.each do |movie|
      .col-sm-6.col-md-3
        .thumbnail
          = link_to (image_tag movie.image_movie.url(:medium), class: 'image'), movie

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">
      <div class="col-md-4">
        <%= image_tag @movie.image_movie.url(:medium)%>
        <div class="table-responsive">
          <table class="table">
            <tbody>
              <tr>
                <td>
                <strong>Title:</strong>
                <%= @movie.title %>
                </td>
              </tr>
              <tr>
                <td>
                  <strong>Description:</strong>
                  <%= @movie.description %>
                </td>
              </tr>
              <tr>
                <td>
                  <strong>Movie length:</strong>
                  <%= @movie.movie_length %>
                </td>
              </tr>
              <tr>
                <td>
                  <strong> Director:</strong>
                  <%= @movie.director%>
                </td>
              </tr>
              <tr>
                <td>
                  <strong>Rating:</strong>
                  <%= @movie.rating%>
                </td>
              </tr>
            </tbody>
          </table>
          <%= link_to "Write a Review", new_movie_review_path(@movie) %>
        </div>
      </div>
      <div class="col-md-7 col-md-offset-1">
        <h1 class="review_title"><%= @movie.title %></h1>
        <p><%= @movie.description %></p>
        <% if @reviews.blank? %>
        <h3>No reviews just yet, would you like to add the first!</h3>
        <% else %>
        <% @reviews.each do |review| %>
          <div class="reviews">
            <!-- 没有将等级⭐️调试出来，视频定格在1:12:30！！ -->
            <div class="star-rating" data-score= <%= review.rating %> ></div>

            <p><%= review.comment %></p>
          </div>

        <% end %>
        <% end %>
        <%= link_to "Write Review", new_movie_review_path(@movie), class: "btn btn-danger"%>
      </div>
    </div>
  </div>
</div>
<%= link_to "Edit", edit_movie_path(@movie) %>
<%= link_to "Back", movies_path %>

<script>
  $('.star-rating').raty({
    path: '/assets/',
    readOnly: true,
    score: functio(){
      return $(this).attr('data-score');
    }
  });
</script>

app/views/pins/_form.html.haml
#pins
  = simple_form_for @pin, html:{multipart:true} do |f|
    -if @pin.errors.any?
      #errors
        %h2
          = pluralize(@pin.errors.count, "error")
          prevented this Pin from saving
          %ul
            - @pin.errors.full_messages.each do |msg|
              %li= msg

    .form-group
      = f.input :image, input_html: { class: 'form-control' }
    .form-group
      = f.input :title, input_html: { class: 'form-control' }
    .form-group
      = f.input :description, input_html:{class: 'form-control'}
    =f.button :submit, class: "btn btn-primary"

app/views/pins/edit.html.haml
#pins
  .col-md-6.col-md-offset-3
    .row
      .panel.panel-default
        .panel-heading
          %h1 Edit Pin
        .panel-body
          %strong.center Current Image
          %br/
          = image_tag @pin.image.url(:medium)
          %br
          = render 'form'

app/views/pins/index.html.haml
#pins
  #pins.transitions-enabled
    - @pins.each do |pin|
      .box.panel.panel-default
        = link_to (image_tag pin.image.url), pin
        .panel-body
          %h2= link_to pin.title, pin
          %p.user
          Submitted by
          = pin.user.email

app/views/pins/new.html.haml
#pins
  .col-md-6.col-md-offset-3
    .row
      .panel.panel-default
        .panel-heading
          %h2 New Pin
        .panel-body
          = render 'form'

app/views/pins/show.html.haml
#pins
  #pin_show.row
    .col-md-8.col-md-offset-2
      .panel.panel-default
        .panel-heading.pin_image
          = image_tag @pin.image.url
        .panel-body
          %h1= @pin.title

          %p= @pin.description

          %p
            Submitted by
            = @pin.user.email
        .panel-footer
          .row
            .col-md-6
              %p.user
              Submitted by
              = @pin.user.email
            .col-md-6
              .btn-group.pull-right
                = link_to like_pin_path(@pin), method: :put, class: "btn btn-default" do
                  %span.glyphicon.glyphicon-heart
                    = @pin.get_upvotes.size
                - if user_signed_in?
                  = link_to "Edit", edit_pin_path(@pin), class: "btn btn-default"
                  = link_to "Delete", pin_path(@pin), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-default"

app/views/reviews/_form.html.erb
<%= simple_form_for([@movie, @review]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :rating %>
    <%= f.input :comment %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>


<%= link_to 'Back', movie_path(@movie) %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Rating</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.rating %></td>
        <td><%= review.comment %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', movie_path(@movie) %>

app/views/reviews/show.html.haml
%p{:id => "notice"}= notice
%p
  %strong Rating:
  = @review.rating
%p
  %strong Comment:
  = @review.comment
%p
  %strong User:
  = @review.user.email
= link_to 'Edit', edit_review_path(@review)
|
= link_to 'Back', reviews_path